### ISSUE TITLE
Invalid CSRF token / Contao 4.9.x

### ISSUE THREAD

**Issue by bytehead** [hofff/contao-rate-it#10]
While using this in Contao 4.9.x, I've always get a `BadRequestHttpException` while voting because of the missing request token: `Invalid CSRF token. Please reload the page and try again.`

Do I miss something or does this extension not work with Contao 4.9?

**Comment by frontendschlampe** [comment]
hmmm ... I'm sorry, but we don't test it already on 4.9 ... maybe you will find the problem?

**Comment by bytehead** [comment]
I'm gonna inspect and provide a PR 😎

**Comment by bytehead** [comment]
Closed in favor of #13.
