### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by bytehead** [hofff/contao-rate-it#11]
While accessing the extension in the backend: 
```
Warning: getimagesize(/web/bundles/hofffcontaorateit/images/star.gif): failed to open stream: No such file or directory
```

The image is actually missing and the `/web` part is possibly hardcoded, as I use `public` as my web directory.

**Comment by frontendschlampe** [comment]
I think, we dropped the icons and we're using an iconfont ... maybe we forgot one?! What do you think @dmolineus

**Comment by bytehead** [comment]
Closing this in favor of #12.

**Comment by dmolineus** [comment]
>  think, we dropped the icons and we're using an iconfont ... maybe we forgot one

We still use it in the backend, but haven't modernized/fixed all stuff of the extension yet.

**Comment by frontendschlampe** [comment]
I don't find it!

**Comment by dmolineus** [comment]
> I don't find it!

Ah, I see. It's generated for the backend menu icon which Contao does not use anymore. :see_no_evil: 

https://github.com/hofff/contao-rate-it/blob/f6d329b46bae99ebad5ca210cd9ae8246dde433e/src/Resources/contao/config/config.php#L31

**Comment by frontendschlampe** [comment]
hehe ... great

so we can delete it someday ;-)
