### ISSUE TITLE
Not Working well with Contao 4.9.8

### ISSUE THREAD

**Issue by max-admina** [hofff/contao-rate-it#14]
Hello togehter,

the rate-It bundle could be installed without problems. Also the old entries of the "cgo-it/rate-it-bundle" are displayed.

Unfortunately the frontend only shows the number of votes and the calculated result for eg: "3,7/5 Sterne (113 Stimmen)". It is not possible to give a new star rating, because the corresponding stars are not displayed.

The associated JavaScript is loaded, but the Webmaster Tools Inspector does not show CSS assignments of the individual elements. Are they possibly not loaded for the frontend? Both no StyleSheets and no InLine-Style (like the old cgo-it/rate-it-bundle version).

Rate-It was set to "Active" in the system settings and also in the article settings (template) and the respective rating element.

So why are there no more stars displayed?

In the frontend only the following code is displayed for the respective element (stars are not visible, only text):

```
<!-- indexer::stop -->
<div id="rateItRating-297-ce-3.7_5" class="hofff-rate-it ce_id block" itemtype="http://schema.org/CreativeWork" itemscope>
    <meta itemprop="name" content="Gesamtbewertung">
        <div class="hofff-rate-it-widget hofff-rate-it-disabled"
         data-rating="3.7"
         data-max="5"
         data-enabled="true"
         data-id="297"
         data-type="ce"
    >
        <i class="hofff-rate-it-icon-rated fas fa-star"></i>
        <i class="hofff-rate-it-icon-unrated far fa-star"></i>
        <i class="hofff-rate-it-icon-half fas fa-star-half-alt"></i>
    </div>
            <div class="hofff-rate-it-message">3,7/5 Sterne (113 Stimmen)</div>
        <span class="rating-microdata" itemtype="http://schema.org/AggregateRating" itemscope itemprop="aggregateRating">
        <meta itemprop="ratingValue" content="3.7">
        <meta itemprop="worstRating" content="0">
        <meta itemprop="bestRating" content="5">
        <meta itemprop="ratingCount" content="113">
    </span>
</div>
<!-- indexer::continue -->
```

**Comment by frontendschlampe** [comment]
You have to integrate Font Awesome to your website because we removed the images. If you don't want to use Font Awesome you have to write your own styles for displaying the stars. We mentioned in the readme und "Changed".

**Comment by max-admina** [comment]
After the offline version of FontAwesome is set up, the stars are displayed.

Maybe FontAwesome should also listened under "Requierements" in the readme?

Thanks for the quick feedback.

**Comment by frontendschlampe** [comment]
> Maybe FontAwesome should also listened under "Requierements" in the readme?

yes ... we have to add it. :-)
