### ISSUE TITLE
Compatibility IE11 / Edge 18 / Mobile Safari on iOS

### ISSUE THREAD

**Issue by bytehead** [hofff/contao-rate-it#15]
Checked version: 0.3.4

The JS does not work on IE11 (Win 10) / Edge 18 (Win 10) and Safari on iOS (tested on iOS 12&13).

- Mouseover is broken
- Click doesn't work

It seems to be an issue with removing the star items completely from the DOM instead of adjusting just css classes.

**Comment by dmolineus** [comment]
I'd appriciate if you test the fix (https://github.com/hofff/contao-rate-it/commit/947756f388c974dabc29e96794bd5741cd2ff098) and confirm that it works https://github.com/hofff/contao-rate-it/tree/fix/mouseout-event.

**Comment by dmolineus** [comment]
Fixed in version 0.3.5.
