### ISSUE TITLE
keine Bewertungen für unterschiedliche Elemente möglich, wenn doppelte Bewertungen deaktiviert

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-rate-it#2]
Wenn doppelte Bewertungen zulassen deaktiviert ist, dann kann ich nur einmal bei irgendeinem Item meine Bewertung abgeben, aber ich darf ja für andere Items Bewertungen abgeben, nur nicht mehrfach für den selben!

**Comment by dmolineus** [comment]
Wie lässt sich dies reproduzieren? Welche Datensätze werden bewertet? Ich kann dies nicht reproduzieren (Bewertung bei News).

**Comment by dmolineus** [comment]
Sollte behoben sein mit b1236a340230d0d041204e068198ed0657033a9b.

**Comment by frontendschlampe** [comment]
Ich kann es jetzt nicht mehr nachvollziehen. Schauen wir mal.
