### ISSUE TITLE
Fehler beim Abgeben einer Bewertung

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-rate-it#3]
Ich bin mir nicht sicher, ob das durch meine Templateänderung aus https://github.com/hofff/contao-rate-it/commit/d7eb4e0ea6cdab2efee8094419d4b88c4c3fd605 kommt, aber die Anzahl der Counts wird nicht automatisch aktualisiert. In der Konsole kommt auch ein JS-Fehler.

**Comment by dmolineus** [comment]
Ja, bitte wieder reparieren....

**Comment by dmolineus** [comment]
Hint: https://github.com/hofff/contao-rate-it/blob/d7eb4e0ea6cdab2efee8094419d4b88c4c3fd605/src/Resources/public/js/script.js#L14

**Comment by frontendschlampe** [comment]
Das hab ich natürlich übersehen.

**Comment by frontendschlampe** [comment]
fixed in https://github.com/hofff/contao-rate-it/commit/21d63d39511f7b4a455b6d383687f3b608aeb4a8
